config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end

  resources :categories, only: [:index]

  resources :images, only: [:index]

  resources :users, only: [:index, :new, :create, :show] do
    resources :ideas, only: [:new, :create, :update, :edit] do
      resources :images, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title

  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of(:title, :description)

  belongs_to :category
  belongs_to :user
  has_many :image_ideas, dependent: :destroy
  has_many :images, through: :image_ideas, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of(:title, :url)

  has_many :image_ideas
  has_many :ideas, through: :image_ideas, dependent: :destroy
end

app/models/image_idea.rb
class ImageIdea < ApplicationRecord
  belongs_to :image
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  has_many :ideas, dependent: :destroy

  enum role: ['default', 'admin']

  has_secure_password
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "#{@category.title} Created!"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:success] = "#{category.title} Deleted!"

    redirect_back(fallback_location: root_path)
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def new
    @categories = Category.all
    @idea = Idea.new
  end

  def show
    render file: '/public/404.html'
  end

  def create
    @idea = @user.ideas.new(idea_params)
    if @idea.save
      flash[:success] = 'Idea Saved!'
      redirect_to user_path(@user)
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if params[:image_id]
      @idea.images << Image.find(params[:image_id])
      redirect_to user_path(current_user)
    elsif @idea.update(idea_params)
      flash[:success] = 'Idea Updated!'
      redirect_to user_path(@user)
    else
      @categories = Category.all
      render :new
    end
  end

  def destroy

  end

  private

  def idea_params
   params.require(:idea).permit(:title, :description, :category_id, :image_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    if params[:idea_id]
      @idea = Idea.find(params[:idea_id])
    end
    @images = Image.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "username/password combo wasn't valid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout Successful!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = 'Username already exists'
      redirect_to new_user_path
    end
  end

  def show
    if User.where(id: params[:id]).empty? || User.find(params[:id]) != current_user
      render file: 'public/404.html'
    else
      @user = User.find(params[:id])
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.submit %>

<% end %>

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>
<div id="create-category-link">
  <%= link_to 'Create New Category', new_admin_category_path %>
</div>
<div class="categories-box">
<% @categories.each do |category| %>
  <div class='category-titles'><%= category.title %>
    <%= link_to admin_category_path(category), method: "delete", data: {confirm: "Are you sure? This will also delete all associated ideas!"} do %>
    <i class="far fa-trash-alt"><span class="hidden"></span></i>
    <% end %>
  </div>
<% end %>
</div>

app/views/admin/categories/new.html.erb
<div class="user-new-background">
  <div class="new_idea">
    <%= render partial: '/admin/categories/form'%>
  </div>
</div>

app/views/categories/index.html.erb
<% if current_admin? %>
  <h1>Categories</h1>
  <% @categories.each do |cat| %>
    <%= cat.title %>
  <% end %>
<% end %>

app/views/ideas/_form.html.erb
<%= form_for [@user, @idea] do |f| %>

<%= f.label :title, id: 'category-label' %>
<%= f.text_field :title %>

<%= f.label :description, id: 'category-label' %>
<%= f.text_area :description %>

<%= f.label :category, id: 'category-label' %>
<%= f.collection_select :category_id, @categories, :id, :title %>

<%= f.submit id: 'create-idea' %>
<% end %>

app/views/ideas/edit.html.erb
<div class="user-new-background">
  <div class="new_idea">
    <%= render partial: '/ideas/form'%>
  </div>
</div>

app/views/ideas/index.html.erb
<%= link_to  'Create Idea', new_user_idea_path(@user) %>
<% @ideas.each do |idea| %>
 <%= link_to idea.title, user_idea_path(@user, idea) %>
<%end%>

app/views/ideas/new.html.erb
<div class="user-new-background">
  <div class="new_idea">
    <%= render partial: '/ideas/form'%>
  </div>
</div>

app/views/images/index.html.erb
<h1>Images!</h1>
<% if current_admin? %>
  <div id="add-new-image-link">
    <%= link_to 'create a new image' %>
  </div>
<% end %>
<div class="user-ideas-box">
<% @images.each do |image| %>
  <div id="image-<%= image.id %>">
      <div class="image-list">
      <%= image.title %>
      <%= image_tag image.url %>

      <% if @idea %>
        <%= form_tag user_idea_path(current_user, @idea), method: 'patch' do %>
        <%= hidden_field_tag :image_id, image.id %>
        <%= submit_tag "Add Image" %>
      <% end %>

    </div>
    <% end %>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Lato:700|Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= render partial: '/partials/nav' %>
    <%= yield %>
    <%= render partial: '/partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer></footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light primary-bg">
<i class="fas fa-crow"></i>
<%= link_to 'Idea Box', root_path, id: 'logo', class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user.nil? %>
      <li class="nav-item">
        <%= link_to 'Sign Up!', new_user_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "I already have an account", login_path, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Go to My Ideas', user_path(current_user), class: 'nav-link' %>
      </li>
      <% end %>
      <% if current_user != nil %>
      <li class="nav-item">
        <%= link_to 'Logout', logout_path, class: "nav-link", id: 'logout-link' %>
      </li>
      <% end %>
      <% if current_admin? %>
      <li class="nav-item">
        <%= link_to 'Categories', admin_categories_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
  
<% end %>

app/views/users/new.html.erb
<div class="user-new-background">
  <div class="new_idea">
    <%= render partial: '/users/form'%>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>
<% if @user.ideas.empty? %>
  <%= link_to 'I have an idea!', new_user_idea_path(@user), class: 'btn-lg' %>
<% else %>
  <%= link_to 'I have another idea!', new_user_idea_path(@user), class: 'btn btn-sm', id: 'idea-button' %>
<% end %>
<div class="user-ideas-box">
  <% @user.ideas.each do |idea| %>
    <div class='user-ideas' 'id='idea-<%= idea.id %>'>
      <div class="user-card-button">

      <p class="btn btn-sm"><%= link_to 'change this idea', edit_user_idea_path(@user, idea), id: 'change-idea' %></p>
      <p class='btn btn-sm'><%= link_to 'Add an Image', user_idea_images_path(@user, idea), id: 'add-image' %></p>
      <p id="idea-title"><%= idea.title %></p>
      <p id='descrip'><%= idea.description %></p>
      <% idea.images.each do |image| %>
        <p class="card-img-bottom" id='card-image'><%= image_tag(image.url, id: 'idea-image') %></p>
        <p id='image-title'><%= image.title %></p>
      <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="parallax text-center">
  <h2 id="parallax-heading"></h2>
</div>

<main>


</main>